"""Add ON DELETE CASCADE to foreign keys

Revision ID: 190dfbff3d90
Revises: 0c5d054a005b
Create Date: 2024-06-13 21:14:31.349096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '190dfbff3d90'
down_revision = '0c5d054a005b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('middle_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_login'), ['login'])
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_role_id_roles'), 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_role_id_roles'), type_='foreignkey')
        batch_op.create_foreign_key('users_ibfk_1', 'roles', ['role_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_users_login'), type_='unique')
        batch_op.alter_column('middle_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
