"""book delete

Revision ID: 489a2fb3ea0e
Revises: 9763dd8f9b96
Create Date: 2024-06-15 17:09:05.797716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '489a2fb3ea0e'
down_revision = '9763dd8f9b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint('visits_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visits_book_id_books'), 'books', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visits_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('visits_ibfk_2', 'books', ['book_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
